"""Step 4 -- write the Verilog-A model: Appendix F (Listing F.1) line for
line, with our fitted scaling coefficients in the *_func functions.

Kept exactly as in the thesis: module structure and terminal order (d, g,
s), W and L instance parameters in um, the ten (L, W) scaling functions,
DeltaL_func(W) and RSD_func(W), Von_eff = max(Von_lin, Von_sat), the
off-state branch, the linear/saturation expressions, the harmonic-mean
blend with a global m, and the overlap/channel charge block (copied
verbatim -- this work fits DC data only, so eps_ox, tox, Lov, Lovch are the
thesis's values, not re-extracted).

Two deliberate differences, both in the RSD line:
  * Unit: RSD_func returns kOhm (like thesis Eq. 3.18 / Table 3.11) and is
    converted with *1e3 to the Ohm that Ids_lin = (G*Vds+Ioff)/(1+RSD*G)
    needs (G in S). Appendix F divides by 100 instead, which is not a unit
    conversion; our G0 values were extracted with RSD in Ohm, so the model
    must use the same RSD.
  * RSD_func is clamped at 0: the linear-in-W fit crosses zero inside the
    width range because RSD is ~0 within the TLM's resolution (see README).

Usage: python step4_export_va.py [variant]   (default: the variant named in
outputs_camcas_thesis/final_variant.txt, else "thesis")
"""
import json
import os
import sys

from common import OUT, PARAMS, VA_PATH

FUNC = {"Von_lin": "von_lin_func", "Von_sat": "von_sat_func", "alpha_lin": "alpha_lin_func",
        "alpha_sat": "alpha_sat_func", "k_lin": "kappa_lin_func", "k_sat": "kappa_sat_func",
        "G0_lin": "G0_lin_func", "G0_sat": "G0_sat_func", "Ioff_lin": "Ioff_lin_func",
        "Ioff_sat": "Ioff_sat_func"}


def f(v):
    return f"{v:.10e}"


def lw_func(p, c):
    name = FUNC[p]
    return f"""analog function real {name};
	input Lm, Wm;
	real Lm, Wm;
	real L2;
	begin
		L2 = Lm*Lm;
		{name} = (({f(c['aW'])} * Wm + {f(c['a0'])}) * L2) +
		         (({f(c['bW'])} * Wm + {f(c['b0'])}) * Lm) +
		         ({f(c['cW'])} * Wm + {f(c['c0'])});
	end
endfunction
"""


def render(coef, variant):
    funcs = "\n".join(lw_func(p, coef["poly"][p]) for p in PARAMS)
    dl, rsd = coef["DeltaL"], coef["RSD_kohm"]
    devs = ", ".join(f"{w}/{l}" for w, l in coef["fit_devices"])
    refined = (",\n// then Von/alpha/kappa/G0 coefficients refined against the fit devices'\n"
               "// measured currents (scripts/camcas_thesis/refine.py)"
               if variant.endswith("_g") else "")
    return f"""// IGZO TFT compact DC model -- CAMCAS, Appendix F of C. de Almeida,
// "Development of IGZO thin-film transistors (TFTs) compact models" (2025),
// re-parameterized on this repository's measurements.
//
// Structure and equations follow Listing F.1 line for line. Every model
// parameter is a function of the instance geometry (W, L in um):
//   Von, alpha, kappa, G0, Ioff (lin & sat):
//       X(L,W) = (aW*W + a0)*L^2 + (bW*W + b0)*L + (cW*W + c0)   (Eqs. 3.5-3.16)
//   DeltaL(W), RSD(W): straight lines in W                      (Eqs. 3.17-3.18)
//   m: one global constant.
// Coefficients: parameters extracted per device with the thesis's
// automatic procedure (Sec. 3.2), scaled with the thesis two-step fit
// (quadratic in L per width, then linear in W){refined}.
// Fit geometries (W/L um): {devs}.
// Held out, never used for fitting: 5/5, 10/5, 10/10. Coefficient variant:
// "{variant}". Valid range: W = 20..160 um, L = 5..20 um, 0 <= VDS.
//
// Differences from Listing F.1 (both on the RSD line, see
// scripts/camcas_thesis/step4_export_va.py): RSD_func is in kOhm and is
// converted with *1e3 (F.1 divides by 100), and it is clamped at 0.
// The charge block is copied verbatim from F.1 and was not re-extracted.
//
// Auto-generated by scripts/camcas_thesis/step4_export_va.py -- regenerate,
// don't hand-edit.

`include "constants.vams"
`include "disciplines.vams"

module tft_camcas_thesis(d, g, s);

inout d, g, s;
electrical d, g, s;

parameter real W = 40; // um
parameter real L = 10; // um

parameter real VH = 5;
parameter real VDSref_lin = 0.1;
parameter real VDSref_sat = 5;

parameter real eps_ox = 3.45e-11;
parameter real tox = 0.1e-6;

parameter real m = {coef['m']:.6g};

real Vgs, Vds, Vgd, Von_lin, Von_sat, Von_eff;
real alpha_lin, alpha_sat;
real G0_lin, G0_sat;
real Ioff_lin, Ioff_sat;
real DeltaL, RSD;
real k_lin, k_sat;
real Lp;
real Ids_sat, Ids_lin;
real Ids_total;
real term_exp;
real G;
real Covs, Covd, CCH;
real Qovs, Qovd, Qch;
real Lov, Lovch;

{funcs}
analog function real DeltaL_func;
	input Wm;
	real Wm;
	begin
		DeltaL_func = {f(dl['s'])} * Wm + {f(dl['i'])}; // [um]
	end
endfunction

analog function real RSD_func;
	input Wm;
	real Wm;
	begin
		RSD_func = {f(rsd['s'])} * Wm + {f(rsd['i'])}; // [kOhm]
	end
endfunction

analog begin

	Vgs = V(g, s);
	Vds = V(d, s);
	Vgd = V(g, d);

	DeltaL = DeltaL_func(W);
	RSD = RSD_func(W) * 1e3; // kOhm -> Ohm
	if (RSD < 0) RSD = 0;

	Von_lin = von_lin_func(L, W);
	Von_sat = von_sat_func(L, W);
	alpha_lin = alpha_lin_func(L, W);
	alpha_sat = alpha_sat_func(L, W);
	k_lin = kappa_lin_func(L, W);
	k_sat = kappa_sat_func(L, W);
	G0_lin = G0_lin_func(L, W);
	G0_sat = G0_sat_func(L, W);
	Ioff_lin = Ioff_lin_func(L, W);
	Ioff_sat = Ioff_sat_func(L, W);

	Lp = L - DeltaL;

	Lov = L*10e-5;
	Lovch = 0.8*L*1e-6;

	Covs = eps_ox * W * 1e-5 * Lov / tox;
	Covd = eps_ox * W * 1e-5 * Lov / tox;
	CCH = eps_ox * W * 1e-5 * Lovch / tox;

	Qovs = Covs * V(g,s);
	Qovd = Covd * V(g,d);
	Qch = CCH * V(g,s);

	if (Von_lin < Von_sat)
		Von_eff = Von_sat;
	else
		Von_eff = Von_lin;

	if (Vgs <= Von_eff) begin
		if (Vds < (Vgs - Von_eff)) begin
			Ids_total = Ioff_lin;
		end
		else begin
			Ids_total = Ioff_sat;
		end
	end
	else begin
		term_exp = exp(k_lin * (Vgs - Von_eff)**alpha_lin);
		G = G0_lin * (W / Lp) * term_exp;
		Ids_lin = (G * Vds + Ioff_lin) / (1 + RSD * G);

		Ids_sat = G0_sat * (W/Lp) * exp(k_sat * (Vgs - Von_eff)**alpha_sat) * (Vgs - Von_eff) + Ioff_sat;

		Ids_total = (Ids_lin**(-m) + Ids_sat**(-m))**(-1/m);
	end

	I(d,s) <+ Ids_total;
	I(g,s) <+ ddt(Qovs + Qch);
	I(g,d) <+ ddt(Qovd);
end

endmodule
"""


def variant_name(argv):
    if len(argv) > 1:
        return argv[1]
    final = os.path.join(OUT, "final_variant.txt")
    return open(final).read().strip() if os.path.exists(final) else "thesis"


def main(variant=None, path=VA_PATH):
    variant = variant or variant_name(sys.argv)
    with open(os.path.join(OUT, f"step3_coefficients_{variant}.json")) as fh:
        coef = json.load(fh)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write(render(coef, variant))
    print(f"Wrote {path} (variant {variant})")
    return path


if __name__ == "__main__":
    main()
