"""Export the 2-hidden-layer model (trained_ANN/deep/weights.json) to
Verilog-A. Same conventions as scripts/export_verilog_a.py (linear output,
[0,1] input scaling, log10 de-standardization) but with two sequential
tanh hidden layers instead of one.

Usage:
    python scripts/export_verilog_a_deep.py
"""
import json
import os

ROOT = os.path.join(os.path.dirname(__file__), "..")
WEIGHTS_PATH = os.path.join(ROOT, "trained_ANN", "deep", "weights.json")
VA_PATH = os.path.join(ROOT, "verilogA", "tft_ann_static_deep.va")


def fmt(x):
    return f"{x:.6f}"


def emit_flat(name, values, per_line):
    lines = []
    for start in range(0, len(values), per_line):
        chunk = values[start:start + per_line]
        parts = [f"{name}[{start + j}] = {fmt(v)};" for j, v in enumerate(chunk)]
        lines.append("\t" + " \t ".join(parts))
    return "\n".join(lines)


def main():
    with open(WEIGHTS_PATH) as f:
        w = json.load(f)
    ni = w["architecture"]["n_inputs"]
    h1, h2 = w["architecture"]["hidden_sizes"]
    assert w["architecture"]["input_order"] == ["VG", "VD", "W", "L"]

    w1, b1 = w["layers"][0]["w"], w["layers"][0]["b"]
    w2, b2 = w["layers"][1]["w"], w["layers"][1]["b"]
    wo, bo = w["output"]["w"][0], w["output"]["b"][0]

    vg_lo, vg_hi = w["input_scaling_minmax"]["VG"]
    vd_lo, vd_hi = w["input_scaling_minmax"]["VD"]
    w_lo, w_hi = w["input_scaling_minmax"]["W"]
    l_lo, l_hi = w["input_scaling_minmax"]["L"]
    y_mean = w["target_transform"]["y_mean_log10_absID"]
    y_std = w["target_transform"]["y_std_log10_absID"]

    w1_flat = [w1[i][k] for i in range(h1) for k in range(ni)]
    w2_flat = [w2[i][k] for i in range(h2) for k in range(h1)]

    va = f"""\
// VerilogA for a-GIZO TFT ANN static model -- 2-HIDDEN-LAYER variant.
// 4 inputs -> {h1} tanh -> {h2} tanh -> 1 linear output.
//
// Same conventions as tft_ann_static.va (single hidden layer): [0,1] input
// scaling, log10(|ID|) standardized target, linear output layer. Trained
// with the same monotonicity penalty + L-balanced loss as the 1-layer
// model, on cleaned_output_meas/merged_output_dataset.csv.
//
// Auto-generated by scripts/export_verilog_a_deep.py from
// trained_ANN/deep/weights.json. Do not hand-edit -- regenerate instead.

`include "constants.h"
`include "disciplines.h"

module tft_ann_static_deep(D, G, S);
inout G, D, S;
electrical D, G, S;

parameter integer NI = {ni};
parameter integer NH1 = {h1};
parameter integer NH2 = {h2};

parameter real w = 40e-6 from [{w_lo:.0f}e-6:{w_hi:.0f}e-6];
parameter real l = 10e-6 from [{l_lo:.0f}e-6:{l_hi:.0f}e-6];

real w1[0:(NI*NH1)-1]; real b1[0:NH1-1]; real y1[0:NH1-1]; real v1[0:NH1-1];
real w2[0:(NH1*NH2)-1]; real b2[0:NH2-1]; real y2[0:NH2-1]; real v2[0:NH2-1];
real wo[0:NH2-1]; real bo;

real vg_s, vd_s, width_s, length_s;
real log_id, id;
integer i, j;

real vg_lo, vg_hi, vd_lo, vd_hi, w_lo, w_hi, l_lo, l_hi;
real y_mean, y_std;

analog begin
	@(initial_step or initial_step("static")) begin

	vg_lo = {fmt(vg_lo)}; vg_hi = {fmt(vg_hi)};
	vd_lo = {fmt(vd_lo)}; vd_hi = {fmt(vd_hi)};
	w_lo  = {w_lo:.1f}e-6; w_hi  = {w_hi:.1f}e-6;
	l_lo  = {l_lo:.1f}e-6; l_hi  = {l_hi:.1f}e-6;
	y_mean = {fmt(y_mean)};
	y_std  = {fmt(y_std)};

	// layer 1 weights: w1[NI*i + k], k in {{0:VG, 1:VD, 2:W, 3:L}}
{emit_flat("w1", w1_flat, ni)}
	// layer 1 bias
{chr(10).join(f"	b1[{i}] = {fmt(b1[i])};" for i in range(h1))}

	// layer 2 weights: w2[NH1*i + k]
{emit_flat("w2", w2_flat, h1)}
	// layer 2 bias
{chr(10).join(f"	b2[{i}] = {fmt(b2[i])};" for i in range(h2))}

	// output weights (linear)
{chr(10).join(f"	wo[{i}] = {fmt(wo[i])};" for i in range(h2))}
	bo = {fmt(bo)};

	end // end of initialization

	vg_s = (V(G,S) - vg_lo) / (vg_hi - vg_lo);
	if (vg_s < 0) vg_s = 0;
	if (vg_s > 1) vg_s = 1;
	vd_s = (V(D,S) - vd_lo) / (vd_hi - vd_lo);
	if (vd_s < 0) vd_s = 0;
	if (vd_s > 1) vd_s = 1;
	width_s = (w - w_lo) / (w_hi - w_lo);
	if (width_s < 0) width_s = 0;
	if (width_s > 1) width_s = 1;
	length_s = (l - l_lo) / (l_hi - l_lo);
	if (length_s < 0) length_s = 0;
	if (length_s > 1) length_s = 1;

	for (i = 0; i < NH1; i = i + 1) begin
		v1[i] = vg_s*w1[NI*i] + vd_s*w1[NI*i+1] + width_s*w1[NI*i+2] + length_s*w1[NI*i+3] + b1[i];
		y1[i] = tanh(v1[i]);
	end

	for (i = 0; i < NH2; i = i + 1) begin
		v2[i] = 0;
		for (j = 0; j < NH1; j = j + 1) begin
			v2[i] = v2[i] + y1[j]*w2[NH1*i+j];
		end
		v2[i] = v2[i] + b2[i];
		y2[i] = tanh(v2[i]);
	end

	log_id = 0;
	for (i = 0; i < NH2; i = i + 1) begin
		log_id = log_id + y2[i]*wo[i];
	end
	log_id = log_id + bo;
	log_id = log_id*y_std + y_mean;   // linear output, then de-standardize
	id = pow(10.0, log_id);

	I(D,S) <+ id;
	I(G,S) <+ 0;
	I(G,D) <+ 0;

	end

endmodule
"""
    os.makedirs(os.path.dirname(VA_PATH), exist_ok=True)
    with open(VA_PATH, "w") as f:
        f.write(va)
    print(f"Wrote {VA_PATH}")


if __name__ == "__main__":
    main()
