"""Merge the 4 per-L ANNs (trained_ANN/per_L/weights_L{5,10,15,20}.json) into
a single Verilog-A module. Each subnetwork has 3 inputs (VG, VD, W) -- L is
dropped as a runtime input, since a Verilog-A instance's `l` parameter is
fixed at elaboration time anyway (never swept during a transient/DC run,
only chosen once per instance).

Merge strategy: `l` is compared against the 4 trained lengths and the
nearest one's weight table (and its own y_mean/y_std, since each
subnetwork was standardized independently) is selected inside
`initial_step` -- this is a one-time, zero-runtime-cost branch, not
something re-evaluated every timestep. Boundaries are the midpoints
between adjacent trained L's: <7.5um -> L=5, 7.5-12.5 -> L=10,
12.5-17.5 -> L=15, >=17.5 -> L=20.

Usage:
    python scripts/export_verilog_a_per_L.py
"""
import json
import os

ROOT = os.path.join(os.path.dirname(__file__), "..")
PER_L_DIR = os.path.join(ROOT, "trained_ANN", "per_L")
VA_PATH = os.path.join(ROOT, "verilogA", "tft_ann_static_per_L.va")
ALL_L = [5, 10, 15, 20]
# nearest-match boundaries (um), midpoints between adjacent trained L's
BOUNDARIES = [7.5, 12.5, 17.5]


def fmt(x):
    return f"{x:.6f}"


def emit_flat_assignments(name, values, per_line=3):
    lines = []
    for start in range(0, len(values), per_line):
        chunk = values[start:start + per_line]
        parts = [f"{name}[{start + j}] = {fmt(v)};" for j, v in enumerate(chunk)]
        lines.append("\t\t" + " \t ".join(parts))
    return "\n".join(lines)


def load_weights(l_value):
    with open(os.path.join(PER_L_DIR, f"weights_L{l_value}.json")) as f:
        return json.load(f)


def branch_block(bucket_idx, l_value, w):
    ni = w["architecture"]["n_inputs"]
    nnhl = w["architecture"]["n_hidden"]
    assert w["architecture"]["input_order"] == ["VG", "VD", "W"]
    wh, bh = w["wh"], w["bh"]
    wo, bo = w["wo"][0], w["bo"][0]
    y_mean = w["target_transform"]["y_mean_log10_absID"]
    y_std = w["target_transform"]["y_std_log10_absID"]

    hlayer_w_flat = [wh[i][k] for i in range(nnhl) for k in range(ni)]
    hlayer_w_block = emit_flat_assignments("hlayer_w", hlayer_w_flat, per_line=ni)
    hlayer_b_block = "\n".join(f"\t\thlayer_b[{i}] = {fmt(bh[i])};" for i in range(nnhl))
    olayer_w_block = "\n".join(f"\t\tolayer_w[{i}] = {fmt(wo[i])};" for i in range(nnhl))

    cond = f"l_bucket == {bucket_idx}"
    return f"""\
	if ({cond}) begin // L = {l_value} um
{hlayer_w_block}
{hlayer_b_block}
{olayer_w_block}
		olayer_b[0] = {fmt(bo)};
		y_mean = {fmt(y_mean)};
		y_std  = {fmt(y_std)};
	end"""


def main():
    weights_by_l = {l: load_weights(l) for l in ALL_L}
    ni = weights_by_l[ALL_L[0]]["architecture"]["n_inputs"]
    nnhl = weights_by_l[ALL_L[0]]["architecture"]["n_hidden"]
    for l in ALL_L:
        assert weights_by_l[l]["architecture"]["n_hidden"] == nnhl, "all per-L nets must share n_hidden to share array sizes"

    vg_lo, vg_hi = weights_by_l[ALL_L[0]]["input_scaling_minmax"]["VG"]
    vd_lo, vd_hi = weights_by_l[ALL_L[0]]["input_scaling_minmax"]["VD"]
    w_lo, w_hi = weights_by_l[ALL_L[0]]["input_scaling_minmax"]["W"]

    branches = "\n".join(branch_block(i, l, weights_by_l[l]) for i, l in enumerate(ALL_L))
    boundary_um = ", ".join(f"{b:g}" for b in BOUNDARIES)

    bucket_logic = "\n".join(
        [f"\tif (l_um < {BOUNDARIES[0]:g}) l_bucket = 0;"] +
        [f"\telse if (l_um < {b:g}) l_bucket = {i+1};" for i, b in enumerate(BOUNDARIES[1:])] +
        [f"\telse l_bucket = {len(ALL_L)-1};"]
    )

    va = f"""\
// VerilogA for a-GIZO TFT ANN static model -- PER-LENGTH ENSEMBLE VARIANT.
//
// Instead of one 4-input (VG,VD,W,L) network, this merges 4 separate
// 3-input (VG,VD,W) networks, one trained per measured channel length
// (L = {", ".join(str(l) for l in ALL_L)} um). Each subnetwork only ever had to fit its
// own W range using its own geometry's data -- no cross-L interpolation,
// no L-imbalance in the training loss. `l` is a device parameter fixed at
// elaboration time, so the nearest trained L's weight table is selected
// once in `initial_step` (nearest-match boundaries at {boundary_um} um) --
// zero runtime cost versus the unified 4-input model.
//
// Architecture per subnetwork follows Eq. (1)-(2) of Bahubalindruni et al.,
// "a-GIZO TFT neural modeling, circuit simulation and validation",
// Solid-State Electronics 105 (2015) 30-36:
//     yh = tanh(x . wh + bh)      hidden layer
//     y  = yh . wo + bo           output layer (LINEAR, no activation)
//
// Auto-generated by scripts/export_verilog_a_per_L.py from
// trained_ANN/per_L/weights_L*.json. Do not hand-edit the weight/bias
// tables -- regenerate instead.

`include "constants.h"
`include "disciplines.h"

module tft_ann_static_per_L(D, G, S);
inout G, D, S;
electrical D, G, S;

parameter integer NI = {ni};      // no. of inputs: VG, VD, W (L selects the subnetwork)
parameter integer NNHL = {nnhl};    // no. of neurons in hidden layer (shared by all 4 subnetworks)
parameter integer NO = 1;

// device geometry (SI units, matching Spectre convention)
parameter real w = 40e-6 from [{w_lo:.0f}e-6:{w_hi:.0f}e-6];  // channel width, training range [{w_lo:.0f},{w_hi:.0f}] um
parameter real l = 10e-6 from [3e-6:22e-6];  // channel length -- nearest of {{{", ".join(str(x) for x in ALL_L)}}} um is used

// hidden layer
real hlayer_w[0:(NI*NNHL)-1];
real hlayer_b[0:NNHL-1];
real hlayer_y[0:NNHL-1];
real hlayer_v[0:NNHL-1];

// output layer (linear)
real olayer_w[0:(NO*NNHL)-1];
real olayer_b[0:NO-1];
real olayer_v[0:NO-1];

real vg_s, vd_s, width_s;   // inputs scaled to [0,1]
real log_id, id;
real gm, gds, temp, temp1;
integer i, ii, jj;
integer l_bucket;
real l_um;

// input scaling (min-max, [0,1]) -- shared across subnetworks, must match
// trained_ANN/ann_train_per_L.py's FEATURE_BOUNDS exactly
real vg_lo, vg_hi, vd_lo, vd_hi, w_lo, w_hi;

// output de-standardization: log10(|ID|) = raw_output*y_std + y_mean
// (each subnetwork has its own y_mean/y_std -- set alongside its weights below)
real y_mean, y_std;

analog begin
	@(initial_step or initial_step("static")) begin

	vg_lo = {fmt(vg_lo)}; vg_hi = {fmt(vg_hi)};
	vd_lo = {fmt(vd_lo)}; vd_hi = {fmt(vd_hi)};
	w_lo  = {w_lo:.1f}e-6; w_hi  = {w_hi:.1f}e-6;

	// select nearest trained L (device parameter, fixed per instance)
	l_um = l * 1e6;
{bucket_logic}

{branches}

	end // end of initialization

	// preprocessing: scale inputs to [0,1] using training bounds, clamped
	// to the training range to avoid extrapolation blow-up outside it
	vg_s = (V(G,S) - vg_lo) / (vg_hi - vg_lo);
	if (vg_s < 0) vg_s = 0;
	if (vg_s > 1) vg_s = 1;

	vd_s = (V(D,S) - vd_lo) / (vd_hi - vd_lo);
	if (vd_s < 0) vd_s = 0;
	if (vd_s > 1) vd_s = 1;

	width_s = (w - w_lo) / (w_hi - w_lo);
	if (width_s < 0) width_s = 0;
	if (width_s > 1) width_s = 1;

	temp  = 0;   // accumulates d(raw_output)/d(vg_s) for gm
	temp1 = 0;   // accumulates d(raw_output)/d(vd_s) for gds

	for (i = 0; i < NNHL; i = i + 1) begin
		hlayer_v[i] = vg_s*hlayer_w[NI*i] + vd_s*hlayer_w[NI*i+1] + width_s*hlayer_w[NI*i+2]
		            + hlayer_b[i];
		hlayer_y[i] = tanh(hlayer_v[i]);
		temp  = temp  + olayer_w[i]*hlayer_w[NI*i]   * (1 - hlayer_y[i]*hlayer_y[i]);
		temp1 = temp1 + olayer_w[i]*hlayer_w[NI*i+1] * (1 - hlayer_y[i]*hlayer_y[i]);
	end

	for (ii = 0; ii < NO; ii = ii + 1) begin
		olayer_v[ii] = 0;
		for (jj = 0; jj < NNHL; jj = jj + 1) begin
			olayer_v[ii] = olayer_v[ii] + hlayer_y[jj]*olayer_w[jj];
		end
		olayer_v[ii] = olayer_v[ii] + olayer_b[ii];   // linear output, no tanh
	end

	// post-processing: undo target standardization and the log10 transform
	log_id = olayer_v[0]*y_std + y_mean;
	id = pow(10.0, log_id);

	// small-signal parameters
	gm  = id * `M_LN10 * y_std * temp  / (vg_hi - vg_lo);
	gds = id * `M_LN10 * y_std * temp1 / (vd_hi - vd_lo);

	I(D,S) <+ id;
	I(G,S) <+ 0;
	I(G,D) <+ 0;

	end

endmodule
"""

    os.makedirs(os.path.dirname(VA_PATH), exist_ok=True)
    with open(VA_PATH, "w") as f:
        f.write(va)
    print(f"Wrote {VA_PATH}")


if __name__ == "__main__":
    main()
