"""Export the trained MLP (outputs/weights.json) to a Verilog-A module for
circuit simulation, following the structure/syntax of the reference ntft.va
example (parameter arrays for wh/bh/wo/bo, tanh hidden layer, analytic
gm/gds) and Eq. (1)-(2) of Bahubalindruni et al. (2015).

Key deviations from the reference example, all necessary for correctness
given how this network was actually trained (not stylistic choices):

  * Output layer is linear (y = yh.wo + bo, no tanh) -- matching the paper's
    Eq. 2 and the requested architecture -- whereas the example applies tanh
    to the output and rescales via (y+1)/2. Copying the example's output
    stage verbatim would silently corrupt every prediction.
  * Inputs are min-max scaled to [0, 1] (VG, VD, W, L), matching how
    src/dataset.py normalized features during training, not the example's
    [-1, 1] convention.
  * The regression target was log10(|ID|), standardized to zero
    mean/unit variance; the module reverses both transforms
    (id = 10 ** (raw_output * y_std + y_mean)) before driving I(D,S).
  * W and L are both module parameters (in meters, SI convention like the
    example's `w`), since the training data spans 19 (W, L) geometries.

Usage:
    python scripts/export_verilog_a.py
"""
import json
import os
import sys

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "outputs")
VA_DIR = os.path.join(os.path.dirname(__file__), "..", "verilogA")
WEIGHTS_PATH = os.path.join(OUT_DIR, "weights.json")
VA_PATH = os.path.join(VA_DIR, "tft_ann_static.va")

if len(sys.argv) > 1:
    WEIGHTS_PATH = sys.argv[1]
if len(sys.argv) > 2:
    VA_PATH = sys.argv[2]


def fmt(x):
    return f"{x:.6f}"


def emit_flat_assignments(name, values, per_line=3):
    lines = []
    for start in range(0, len(values), per_line):
        chunk = values[start:start + per_line]
        parts = [f"{name}[{start + j}] = {fmt(v)};" for j, v in enumerate(chunk)]
        lines.append("\t" + " \t ".join(parts))
    return "\n".join(lines)


def main():
    with open(WEIGHTS_PATH) as f:
        w = json.load(f)

    ni = w["architecture"]["n_inputs"]
    nnhl = w["architecture"]["n_hidden"]
    no = w["architecture"]["n_outputs"]
    assert w["architecture"]["input_order"] == ["VG", "VD", "W", "L"]

    wh = w["wh"]   # [nnhl][ni]
    bh = w["bh"]   # [nnhl]
    wo = w["wo"][0]  # [nnhl]  (single output)
    bo = w["bo"][0]

    vg_lo, vg_hi = w["input_scaling_minmax"]["VG"]
    vd_lo, vd_hi = w["input_scaling_minmax"]["VD"]
    w_lo, w_hi = w["input_scaling_minmax"]["W"]
    l_lo, l_hi = w["input_scaling_minmax"]["L"]

    y_mean = w["target_transform"]["y_mean_log10_absID"]
    y_std = w["target_transform"]["y_std_log10_absID"]

    hlayer_w_flat = [wh[i][k] for i in range(nnhl) for k in range(ni)]
    olayer_w_flat = wo

    hlayer_w_block = emit_flat_assignments("hlayer_w", hlayer_w_flat, per_line=ni)
    hlayer_b_block = "\n".join(f"\thlayer_b[{i}] = {fmt(bh[i])};" for i in range(nnhl))
    olayer_w_block = "\n".join(f"\tolayer_w[{i}] = {fmt(olayer_w_flat[i])};" for i in range(nnhl))

    va = f"""\
// VerilogA for a-GIZO TFT ANN static model (MLP: 4 inputs -> {nnhl} tanh
// hidden neurons -> linear output), trained on ID = f(VG, VD, W, L).
//
// Architecture follows Eq. (1)-(2) of Bahubalindruni et al., "a-GIZO TFT
// neural modeling, circuit simulation and validation", Solid-State
// Electronics 105 (2015) 30-36:
//     yh = tanh(x . wh + bh)      hidden layer
//     y  = yh . wo + bo           output layer (LINEAR, no activation)
//
// Regression target is log10(|ID|), standardized to zero mean / unit
// variance during training; this module reverses both transforms to
// recover ID in amperes. Inputs are min-max scaled to [0,1] using the
// exact training bounds baked in below (see outputs/weights.json).
//
// Auto-generated by scripts/export_verilog_a.py from outputs/weights.json.
// Do not hand-edit the weight/bias tables -- regenerate instead.

`include "constants.h"
`include "disciplines.h"

module tft_ann_static(D, G, S);
inout G, D, S;
electrical D, G, S;

parameter integer NI = {ni};      // no. of inputs: VG, VD, W, L
parameter integer NNHL = {nnhl};    // no. of neurons in hidden layer
parameter integer NO = {no};       // no. of outputs (ID)

// device geometry (SI units, matching Spectre convention)
parameter real w = 40e-6 from [{w_lo:.0f}e-6:{w_hi:.0f}e-6];  // channel width, training range [{w_lo:.0f},{w_hi:.0f}] um
parameter real l = 10e-6 from [{l_lo:.0f}e-6:{l_hi:.0f}e-6];  // channel length, training range [{l_lo:.0f},{l_hi:.0f}] um

// hidden layer
real hlayer_w[0:(NI*NNHL)-1];
real hlayer_b[0:NNHL-1];
real hlayer_y[0:NNHL-1];
real hlayer_v[0:NNHL-1];

// output layer (linear)
real olayer_w[0:(NO*NNHL)-1];
real olayer_b[0:NO-1];
real olayer_v[0:NO-1];

real vg_s, vd_s, width_s, length_s;   // inputs scaled to [0,1]
real log_id, id;
real gm, gds, temp, temp1;
integer i, ii, jj;

// input scaling (min-max, [0,1]) -- must match src/dataset.py exactly
real vg_lo, vg_hi, vd_lo, vd_hi, w_lo, w_hi, l_lo, l_hi;

// output de-standardization: log10(|ID|) = raw_output*y_std + y_mean
real y_mean, y_std;

analog begin
	@(initial_step or initial_step("static")) begin

	vg_lo = {fmt(vg_lo)}; vg_hi = {fmt(vg_hi)};
	vd_lo = {fmt(vd_lo)}; vd_hi = {fmt(vd_hi)};
	w_lo  = {w_lo:.1f}e-6; w_hi  = {w_hi:.1f}e-6;
	l_lo  = {l_lo:.1f}e-6; l_hi  = {l_hi:.1f}e-6;

	y_mean = {fmt(y_mean)};
	y_std  = {fmt(y_std)};

	// hidden layer weights: hlayer_w[NI*i + k], k in {{0:VG, 1:VD, 2:W, 3:L}}
{hlayer_w_block}

	// hidden layer bias
{hlayer_b_block}

	// output layer weights
{olayer_w_block}

	// output layer bias
	olayer_b[0] = {fmt(bo)};

	end // end of initialization

	// preprocessing: scale inputs to [0,1] using training bounds, clamped
	// to the training range to avoid extrapolation blow-up outside it
	vg_s = (V(G,S) - vg_lo) / (vg_hi - vg_lo);
	if (vg_s < 0) vg_s = 0;
	if (vg_s > 1) vg_s = 1;

	vd_s = (V(D,S) - vd_lo) / (vd_hi - vd_lo);
	if (vd_s < 0) vd_s = 0;
	if (vd_s > 1) vd_s = 1;

	width_s = (w - w_lo) / (w_hi - w_lo);
	if (width_s < 0) width_s = 0;
	if (width_s > 1) width_s = 1;

	length_s = (l - l_lo) / (l_hi - l_lo);
	if (length_s < 0) length_s = 0;
	if (length_s > 1) length_s = 1;

	temp  = 0;   // accumulates d(raw_output)/d(vg_s) for gm
	temp1 = 0;   // accumulates d(raw_output)/d(vd_s) for gds

	for (i = 0; i < NNHL; i = i + 1) begin
		hlayer_v[i] = vg_s*hlayer_w[NI*i]   + vd_s*hlayer_w[NI*i+1]
		            + width_s*hlayer_w[NI*i+2] + length_s*hlayer_w[NI*i+3]
		            + hlayer_b[i];
		hlayer_y[i] = tanh(hlayer_v[i]);
		temp  = temp  + olayer_w[i]*hlayer_w[NI*i]   * (1 - hlayer_y[i]*hlayer_y[i]);
		temp1 = temp1 + olayer_w[i]*hlayer_w[NI*i+1] * (1 - hlayer_y[i]*hlayer_y[i]);
	end

	for (ii = 0; ii < NO; ii = ii + 1) begin
		olayer_v[ii] = 0;
		for (jj = 0; jj < NNHL; jj = jj + 1) begin
			olayer_v[ii] = olayer_v[ii] + hlayer_y[jj]*olayer_w[jj];
		end
		olayer_v[ii] = olayer_v[ii] + olayer_b[ii];   // linear output, no tanh
	end

	// post-processing: undo target standardization and the log10 transform
	log_id = olayer_v[0]*y_std + y_mean;
	id = pow(10.0, log_id);

	// small-signal parameters (chain rule through tanh hidden layer, the
	// linear output layer, the log10 back-transform, and the [0,1] input
	// scaling -- d(vg_s)/d(VG) = 1/(vg_hi-vg_lo), same for vd_s)
	gm  = id * `M_LN10 * y_std * temp  / (vg_hi - vg_lo);
	gds = id * `M_LN10 * y_std * temp1 / (vd_hi - vd_lo);

	I(D,S) <+ id;
	I(G,S) <+ 0;
	I(G,D) <+ 0;

	end

endmodule
"""

    os.makedirs(VA_DIR, exist_ok=True)
    with open(VA_PATH, "w") as f:
        f.write(va)
    print(f"Wrote {VA_PATH}")


if __name__ == "__main__":
    main()
