"""Export the unified CAMCAS model (outputs_camcas/camcas_unified_params.json,
from scripts/fit_camcas_unified.py) to verilogA/tft_camcas_unified.va.

One fixed parameter set for every (w, l) -- geometry enters only through
W/L' and RSD = Rsw/W -- so unlike tft_camcas_model.va there are no
per-device tables and no nearest-match selection. Equations are identical
to scripts/camcas_unified.py, plus two circuit-robustness details that
don't affect any measured bias point (VDS >= 0.1 V or VDS = 0 noise floor):
  * source/drain swap for VDS < 0 (symmetric device),
  * Ioff scaled by tanh(VDS / 20 mV) so no current flows at VDS = 0.

`--check` compiles the generated file with verilogae (OpenVAF) and compares
it against scripts/camcas_unified.py on every measured bias point.

Usage:
    python scripts/export_verilog_a_camcas_unified.py [--check]
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
PARAMS_PATH = os.path.join(REPO, "outputs_camcas", "camcas_unified_params.json")
VA_PATH = os.path.join(REPO, "verilogA", "tft_camcas_unified.va")

TEMPLATE = """\
// VerilogA for a-IGZO TFT -- UNIFIED CAMCAS compact DC model.
//
// Semi-empirical unified drain-current model from Carolina de Almeida's
// thesis "Development of IGZO thin-film transistors (TFTs) compact models"
// (2025), Sec. 2.3.4 / Appendix F (CAMCAS), fit to this repo's measured data
// (data_cleaned_2) with ONE fixed parameter set valid for every geometry:
// (w, l) enter only through W/L' (L' = L - DeltaL) and RSD = Rsw/W. No
// per-device tables, no (L, W) polynomial surfaces.
//
//   G(VGS) = GH * (W/L') * exp( s*((x/xH)^alpha - 1)/alpha ),
//            x = VGS - Von, xH = VH - Von          (per branch: lin, sat)
//   I_lin  = G_lin*VDS / (1 + RSD*G_lin)
//   I_sat  = G_sat * (VGS - Von_sat)
//   IDS    = (I_lin^-m + I_sat^-m)^(-1/m) + Ioff
//
// The G expression is the thesis's G0*(W/L')*exp(kappa*x^alpha) rewritten
// around the reference point VGS = VH (kappa = s/(alpha*xH^alpha),
// G0 = GH*exp(-kappa*xH^alpha)) -- same curve, better-conditioned fit.
// Thesis-notation equivalents of the values below:
//   lin: Von={t_lin_Von:.4f} V  alpha={t_lin_alpha:.4f}  kappa={t_lin_kappa:.4f}  G0={t_lin_G0:.4e} S
//   sat: Von={t_sat_Von:.4f} V  alpha={t_sat_alpha:.4f}  kappa={t_sat_kappa:.4f}  G0={t_sat_G0:.4e} S
//
// Fit jointly (linear transfer, saturation transfer and output curves, in
// log10|ID|) to the {n_golden} "golden" devices that agree with the process
// consensus: {golden}. DeltaL comes from a width-normalized TLM over those
// devices. Leave-one-device-out cross-validation: mean held-out error
// {loo:.3f} decades of log10|ID| (geometry never seen by the fit). See
// outputs_camcas/README.md for accuracy vs. this repo's ANN.
//
// Robustness additions (no effect at measured bias points): source/drain
// swap for VDS < 0; Ioff scaled by tanh(VDS/20mV) so I=0 at VDS=0.
//
// Auto-generated by scripts/export_verilog_a_camcas_unified.py -- regenerate,
// don't hand-edit.

`include "constants.h"
`include "disciplines.h"

module tft_camcas_unified(D, G, S);
inout D, G, S;
electrical D, G, S;

parameter real w = 40e-6 from [5e-6:160e-6];  // channel width (m)
parameter real l = 10e-6 from [5e-6:20e-6];   // channel length (m)

// unified model parameters -- the same for every device
parameter real VH        = {VH:.6g};          // reference gate voltage (V)
parameter real Von_lin   = {Von_lin:.8g};
parameter real Von_sat   = {Von_sat:.8g};
parameter real lnGH_lin  = {lnGH_lin:.8g};    // ln(S) per unit W/L'
parameter real lnGH_sat  = {lnGH_sat:.8g};
parameter real s_lin     = {s_lin:.8g};
parameter real s_sat     = {s_sat:.8g};
parameter real alpha_lin = {alpha_lin:.8g};
parameter real alpha_sat = {alpha_sat:.8g};
parameter real DeltaL    = {DeltaL:.8g};      // um (negative: L_eff > L_drawn)
parameter real Rsw       = {Rsw:.8g};         // Ohm*um  (RSD = Rsw/W)
parameter real m_smooth  = {m:.8g};
parameter real Ioff      = {Ioff:.8e};        // A

real Wm, Lp, wl, rsd;
real vgs, vds, sgn;
real x, g_lin, g_sat, G_lin, i_lin, i_sat, lo, hi, ids;

analog function real gsheet;
	input vg, von, lnGH, s, alpha, vh;
	real vg, von, lnGH, s, alpha, vh, xx, arg;
	begin
		xx = vg - von;
		if (xx <= 1.0e-9)
			gsheet = 0.0;
		else begin
			arg = lnGH + s * (pow(xx / (vh - von), alpha) - 1.0) / alpha;
			if (arg < -700.0) arg = -700.0;
			gsheet = exp(arg);
		end
	end
endfunction

analog begin
	// parameter-only terms; no initial_step block so OpenVAF (ngspice/Xyce
	// OSDI) compiles this as well as Spectre
	Wm = w * 1.0e6;
	Lp = l * 1.0e6 - DeltaL;
	if (Lp < 0.5) Lp = 0.5;
	wl = Wm / Lp;
	rsd = Rsw / Wm;

	if (V(D,S) >= 0.0) begin
		sgn = 1.0;
		vgs = V(G,S);
		vds = V(D,S);
	end else begin
		sgn = -1.0;
		vgs = V(G,D);
		vds = V(S,D);
	end

	g_lin = gsheet(vgs, Von_lin, lnGH_lin, s_lin, alpha_lin, VH);
	g_sat = gsheet(vgs, Von_sat, lnGH_sat, s_sat, alpha_sat, VH);
	x = vgs - Von_sat;
	if (x < 0.0) x = 0.0;

	G_lin = g_lin * wl;
	i_lin = G_lin * vds / (1.0 + rsd * G_lin);
	i_sat = g_sat * wl * x;
	if (i_lin < 1.0e-30) i_lin = 1.0e-30;
	if (i_sat < 1.0e-30) i_sat = 1.0e-30;

	// harmonic mean (i_lin^-m + i_sat^-m)^(-1/m), overflow-safe form
	lo = min(i_lin, i_sat);
	hi = max(i_lin, i_sat);
	ids = lo * pow(1.0 + pow(lo / hi, m_smooth), -1.0 / m_smooth)
	      + Ioff * tanh(vds / 0.02);

	I(D,S) <+ sgn * ids;
end

endmodule
"""


def render():
    with open(PARAMS_PATH) as f:
        fit = json.load(f)
    p = dict(fit["params"])
    import math
    p["Ioff"] = math.exp(p.pop("lnIoff"))
    t = {f"t_{br}_{k}": v for br, d in fit["thesis_form"].items() for k, v in d.items()}
    golden = ", ".join(f"{w:g}/{l:g}" for w, l in fit["golden_devices"])
    return TEMPLATE.format(VH=fit["VH"], n_golden=len(fit["golden_devices"]),
                           golden=f"W/L = {golden} um", loo=fit["loo_cv_mean_heldout_mae_dec"],
                           **p, **t)


def check(va_text):
    """Compile with verilogae (OpenVAF) and compare to the Python model."""
    import tempfile

    import numpy as np
    import pandas as pd
    import verilogae

    sys.path.insert(0, HERE)
    from camcas_unified import UnifiedParams, ids

    with open(PARAMS_PATH) as f:
        fit = json.load(f)
    params = UnifiedParams(**fit["params"])
    va_params = {k: v for k, v in fit["params"].items() if k not in ("m", "lnIoff")}
    va_params.update(VH=fit["VH"], m_smooth=params.m, Ioff=float(np.exp(params.lnIoff)))
    src = va_text.replace('"constants.h"', '"constants.vams"').replace(
        '"disciplines.h"', '"disciplines.vams"').replace(
        "lo, hi, ids;", "lo, hi;\n(*retrieve*) real ids;")
    with tempfile.NamedTemporaryFile("w", suffix=".va", delete=False) as tmp:
        tmp.write(src)
    model = verilogae.load(tmp.name)
    fn = model.functions["ids"]

    df = pd.read_csv(os.path.join(REPO, "data_cleaned_2", "merged_ann_dataset.csv"))
    df = df[df.VD >= 0.1]
    va = np.empty(len(df))
    for (W, L), g in df.groupby(["W", "L"]):
        out = fn.eval(temperature=300.0, voltages={"br_GS": g.VG.to_numpy(),
                                                   "br_DS": g.VD.to_numpy(),
                                                   "br_GD": (g.VG - g.VD).to_numpy()},
                      w=W * 1e-6, l=L * 1e-6, **va_params)
        va[df.index.get_indexer(g.index)] = out
    py = ids(df.VG, df.VD, df.W, df.L, params)
    rel = np.abs(va - py) / py
    print(f"Verilog-A vs Python on {len(df)} measured bias points (VD >= 0.1 V): "
          f"max rel diff {rel.max():.2e}, median {np.median(rel):.2e}")
    return rel.max()


def main():
    va = render()
    os.makedirs(os.path.dirname(VA_PATH), exist_ok=True)
    with open(VA_PATH, "w") as f:
        f.write(va)
    print(f"Wrote {VA_PATH}")
    if "--check" in sys.argv:
        check(va)


if __name__ == "__main__":
    main()
