"""Emit an ngspice subcircuit that is a line-for-line transliteration of
verilogA/ntft_full.va (ID + CGD + CGS ANNs).

No Verilog-A compiler (OpenVAF/ADMS) is available here, so the .va is
rewritten into ngspice behavioural sources. The weights come from the same
parser as src/va_model.py, i.e. straight out of the .va text, and every
step of the .va's analog block is reproduced:

  * min-max scaling of V(G,S), V(D,S), W, L to [0,1] with the hard clamps
  * tanh -> tanh -> linear for each net
  * ID = 10^(out*std + mean), as a current D->S
  * CGD/CGS = (out*std + mean) * W[um]*L[um] * 1e-15 F, floored at 0
  * form='qcv': I(G,D) <+ ddt(cgd*V(G,D)), I(G,S) <+ ddt(cgs*V(G,S)) -- the
    .va's Q = C(V)*V charge, whose incremental capacitance goes negative at
    the turn-on knee (see src/tran.py)
  * form='cdv' (default): I = C*ddt(V), as verilogA/ntft_full_cdv.va

W and L are folded into the first-layer biases, so there is one subcircuit
per geometry. Each neuron is a .func, so every net is one closed-form
expression of V(G,S) and V(D,S): no internal unknowns, and because the inputs
are clamped exactly as in the .va, ID and C stay bounded for any Newton
iterate. The ddt() is done by ngspice's own integrator: Q (or V) is written
onto an ideal-source node and differentiated by a 1 pF capacitor whose current
is sensed by a 0 V source.

This is exact but slow (~10 ms per device evaluation: the symbolic
derivative of a 4-32-16-1 net is huge), so it is used to cross-check
src/tran.py, not for the large circuits.
"""
import numpy as np

from .va_model import TFTModel

LN10 = float(np.log(10.0))


def _fmt(x):
    return f"{x:.9g}"


def _lin(terms, bias):
    """'bias + w1*x1 + ...' with zero weights dropped."""
    s = _fmt(bias)
    for w, x in terms:
        if w == 0.0:
            continue
        s += (" + " if w >= 0 else " - ") + f"{_fmt(abs(w))}*{x}"
    return s


def subckt_name(w, l, form="cdv"):
    name = f"ntft_w{w * 1e6:g}_l{l * 1e6:g}".replace(".", "p")
    return name if form == "cdv" else name + "_qcv"


def subckt(w, l, m=None, form="cdv"):
    """ngspice .subckt text for one (W,L). Ports: d g s."""
    m = m or TFTModel()
    ws = min(max((w - m.w_lo) / (m.w_hi - m.w_lo), 0.0), 1.0)
    ls = min(max((l - m.l_lo) / (m.l_hi - m.l_lo), 0.0), 1.0)
    area = (w * 1e6) * (l * 1e6) * 1e-3 * 1e-12
    name = subckt_name(w, l, form)
    # clamped inputs (vg_s, vd_s of the .va) as subcircuit-local functions
    L = [f".subckt {name} d g s",
         f"* a-IGZO TFT, W={w * 1e6:g}um L={l * 1e6:g}um, from verilogA/ntft_full.va",
         f".func vgs_s() {{min(max((v(g,s) - ({_fmt(m.vg_lo)}))/{_fmt(m.vg_hi - m.vg_lo)}, 0), 1)}}",
         f".func vds_s() {{min(max((v(d,s) - ({_fmt(m.vd_lo)}))/{_fmt(m.vd_hi - m.vd_lo)}, 0), 1)}}"]

    def net(tag):
        n = m.nets[tag]
        h1, h2 = n["W1"].shape[0], n["W2"].shape[0]
        for i in range(h1):
            a = n["W1"][i]
            c = a[2] * ws + a[3] * ls + n["b1"][i]
            L.append(f".func {tag}1_{i}() {{tanh({_lin([(a[0], 'vgs_s()'), (a[1], 'vds_s()')], c)})}}")
        for j in range(h2):
            terms = [(n["W2"][j, i], f"{tag}1_{i}()") for i in range(h1)]
            L.append(f".func {tag}2_{j}() {{tanh({_lin(terms, n['b2'][j])})}}")
        # de-standardised output, folded: out*std + mean
        terms = [(n["wo"][j] * n["std"], f"{tag}2_{j}()") for j in range(h2)]
        return _lin(terms, n["bo"] * n["std"] + n["mean"])

    log_id = net("id")
    L.append(f"bid d s i=exp({_fmt(LN10)}*({log_id}))")
    for tag, a, b in (("cgd", "g", "d"), ("cgs", "g", "s")):
        c_expr = f"{_fmt(area)}*max({net(tag)}, 0)"
        if form == "qcv":
            # Q*1e12 on q<tag>; the 1 pF cap returns dQ/dt through v<tag>
            L.append(f"bq{tag} q{tag} 0 v=1e12*{c_expr}*v({a},{b})")
            L.append(f"cq{tag} q{tag} k{tag} 1p")
            L.append(f"v{tag} k{tag} 0 0")
            L.append(f"bi{tag} {a} {b} i=i(v{tag})")
        else:
            # V(a,b) on q<tag>; the 1 pF cap returns 1e-12*dV/dt through v<tag>
            L.append(f"bq{tag} q{tag} 0 v=v({a},{b})")
            L.append(f"cq{tag} q{tag} k{tag} 1p")
            L.append(f"v{tag} k{tag} 0 0")
            L.append(f"bi{tag} {a} {b} i=1e12*{c_expr}*i(v{tag})")
    L.append(f".ends {name}")
    return "\n".join(L) + "\n"


def library(geoms, form="cdv"):
    m = TFTModel()
    hdr = "* ngspice transliteration of verilogA/ntft_full.va -- generated by src/ngspice_tft.py\n"
    return hdr + "\n".join(subckt(w, l, m, form) for w, l in sorted(set(geoms)))
